### ISSUE TITLE
ACCESS_FINE_LOCATION allows an app to access precise location

### ISSUE THREAD

**Issue by XRotoX** [Wiqaytna-app/wiqaytna_android#35]
Right in the manifest.xml file you mentioned that "..., the ACCESS_FINE_LOCATION doesn't give any access to the user's GPS location.". As in the android developer documentation it says: "Allows an app to access precise location." 
https://developer.android.com/reference/android/Manifest.permission#ACCESS_FINE_LOCATION

**Comment by Abdelwahad** [comment]
Theses permissions are **requiered** for Bluetooth, and indeed, we don't use GPS :

Bluetooth permissions
In order to use Bluetooth features in your application, you must declare two permissions. The first of these is BLUETOOTH. You need this permission to perform any Bluetooth communication, such as requesting a connection, accepting a connection, and transferring data.

The other permission that you must declare is ACCESS_FINE_LOCATION. Your app needs this permission because a Bluetooth scan can be used to gather information about the location of the user. This information may come from the user's own devices, as well as Bluetooth beacons in use at locations such as shops and transit facilities.
